### PR TITLE
Share Kit Android Library

### PR DESCRIPTION
**Pull request by mul1sh**
Fixes the issue https://github.com/hellobloom/share-kit/issues/44

### CODE REVIEW

**Comment by edhedges** [comment]
Hey @mul1sh I just followed your instructions and was able to get a working demo app up and running that properly opened up my Bloom app to the sharing request view! Great work :)

I have a couple questions:
1. Could you add some more explicit instructions under the Installation section for incorporating into a brand new Android Studio app? I'm not experienced with Android development and thus it took me a bit to understand that I needed to set an id for my MainActivity layout to be able to use it when creating a new EmptyActivity project. I specifically used `ConstraintLayout` instead of `LinerLayout` and explicitly set an id in the layout .xml file.
2. I'm assuming it's possible to register a callback-url for Bloom app to redirect back to. Can this be simplified and included as part of the share-kit-android library? If not, is this something that the consuming app would be responsible for?

**Comment by mul1sh** [comment]
@edhedges  thanks  :) and done.

I've updated the README to have more explicit instructions for adding the library in a new Android Studio project/app.

Also the `callback-url` is already supported by the `share-kit-android` library, I simply camel-cased it as `callbackUrl` instead of `callback-url` inline with android coding standards. I've updated the instructions to be clear about this too and as long as the user's app is correctly [deep-linked](https://developer.android.com/training/app-links/deep-linking) then it will be opened by the Bloom App after the request is processed.

**Comment by edhedges** [comment]
@mul1sh I saw the `callback-url`, but I was thinking it'd be cool if the app/example app that's consuming share-kit-android could register itself to handle the value specified in the `callback-url` so that the flow would look like:
1. app/example app display the share-kit button
2. user taps button and it opens Bloom app
3. user shares button and the `callback-url` is invoked
4. app/example app handles the `callback-url` and opens is navigated back to to continue whatever it needed the Bloom integration for.

Does this make sense?

**Comment by mul1sh** [comment]
@edhedges  yes it makes a lot of sense and again this depends on how well the user has integrated deep-linking in their app and how they handle the Bloom response.

So for the flow to work like this, the user's app has to first save the instance state on opening the bloom button and then retrieve it on `callback-url` invoking [like this](https://www.intertech.com/Blog/saving-and-retrieving-android-instance-state-part-1/). And then after retrieving the state, the user/user's app is responsible for determining where to navigate in the app based on the Bloom response from the `receiving url`.

So again this is do-able, but it is not something the `share-kit-android` library can handle because the library has no way of maintaining the state of the app where its implemented since this state is app specific and the library has no access to this.  I hope this is clear, but i'll gladly clarify even further if you want me to :)

**Comment by edhedges** [comment]
@mul1sh
Thanks for the clarification. That’s what I assumed, but I was just wondering if it could be made easier via the share-kit-android lib. I’ll go ahead and merge this as it’s feature complete!

**Comment by mul1sh** [comment]
@edhedges awesome thanks :)

**Pull request merged**
